import type { Metadata } from "next";
import Header from "@/app/ui/header/header";
import { Inter } from "next/font/google";
import "./globals.css";
import style from "@/app/layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className={style.Homepage_layout__left}>
            <div className={style.Homepage_content__wrapper}>
              <h3>Project introduction</h3>
              <p>xxx</p>
              <p>xxx</p>
            </div>
          </div>
          <div className={style.Homepage_layout__right}>
            <div className={style.Homepage_layout__rightcontainer}>
              <Header />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
