import type { Metadata } from "next";
import Header from "@/app/ui/header/header";
import { Inter } from "next/font/google";
import "./globals.css";
import style from "@/app/layout.module.scss";
import ProjectIntro from "@/app/ui/projectIntro/projectIntro";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * this layout is the root page layout
 * @param {ReactNode} children the children of this layout
 * @returns {React.FC} a functional component
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className={style.Homepage_layout__left}>
            <ProjectIntro />
          </div>
          <div className={style.Homepage_layout__right}>
            <div className={style.Homepage_layout__rightcontainer}>
              <div className={style.Homepage_layout__rightheadercontainer}>
                <Header />
              </div>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
